### PR TITLE
Upgrade to .net/ef 6.0

### PR DESCRIPTION
**Pull request by stavroskasidis**
Upgraded to 6.0 as it was not working.

### CODE REVIEW

**Comment by walisc** [comment]
Hi @stavroskasidis .Thanks for this! Will look into this over the weekend, and merge if everything look good. Thanks!

**Comment by walisc** [comment]
Hi @stavroskasidis. Have only managed to start looking at this now. Could you possibly update the example project to use .net 6.0 as well and make sure it's working fine. p.s also going to try add some tests to the 3.1 version we can then use to test this version (and future ones) as well. Thanks!

**Comment by stavroskasidis** [comment]
Sure

**Comment by stavroskasidis** [comment]
Updated the sample project (it seems to work as expected)

**Comment by walisc** [comment]
> Updated the sample project (it seems to work as expected)

Thanks @stavroskasidis !

**Pull request merged**
